NAME	= btc
CXX		= c++

CXXFLAGS	= -Wall -Wextra -Werror -std=c++98

SRC =	main.cpp \
		BitcoinExchange.cpp

OBJ = $(SRC:.cpp=.o)

all:$(NAME)

$(NAME):$(OBJ)
	$(CXX) $(CXXFLAGS) $^ -o $@

clean:
	$(RM) $(OBJ)

fclean:clean
	$(RM) $(NAME)

re:fclean all

debug:fclean
debug:CXXFLAGS+= -g -fsanitize=address
debug:all

.PHONY:
	all clean fclean re
