all:
	bash test.sh

clean:
	rm -f PmergeMe

fclean:clean
	make fclean -C ../
	rm -rf ./log
	

p:
	make pair -C ..
 
s:
	make separate -C ..

f:
	make first -C ..

sort:
	make sort -C ..

re:
	make re -C ..

infinity:
	bash infinity.sh